name: Generate Snake Commits

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Gerar snake.svg
        uses: Platane/snk@v3
        with:
          github_user_name: michaelfernan
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Criar branch output e commitar SVG
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git fetch origin
          git switch -c output || git checkout output
          mkdir -p dist
          cp dist/github-contribution-grid-snake.svg github-contribution-grid-snake.svg
          git add github-contribution-grid-snake.svg
          git commit -m "chore: primeira cobrinha 🐍" || echo "nada pra commitar"
          git push origin output
